
INSERT INTO TO_DO (ID, OWNER, DESCRIPTION, START_DATE, IS_ENABLED) VALUES (1,'Santiago', 'Learn React', NOW(), false);
INSERT INTO TO_DO (ID, OWNER, DESCRIPTION, START_DATE, IS_ENABLED) VALUES (2,'Santiago', 'Learn Angular', NOW(), false);
INSERT INTO TO_DO (ID, OWNER, DESCRIPTION, START_DATE, IS_ENABLED) VALUES (3,'Santiago', 'Learn AWS', NOW(), false);
INSERT INTO TO_DO (ID, OWNER, DESCRIPTION, START_DATE, IS_ENABLED) VALUES (4,'Julian', 'Learn Spring', NOW(), false);